/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.org.openjfx.javafx.controls)
    api(libs.org.openjfx.javafx.fxml)
    api(libs.org.openjfx.javafx.web)
    api(libs.org.openjfx.javafx.swing)
    api(libs.org.controlsfx.controlsfx)
    api(libs.com.dlsc.formsfx.formsfx.core)
    api(libs.net.synedra.validatorfx)
    api(libs.org.kordamp.ikonli.ikonli.javafx)
    api(libs.org.kordamp.bootstrapfx.bootstrapfx.core)
    api(libs.eu.hansolo.tilesfx)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.api)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.engine)
}

group = "com.casual.flawless"
version = "1.0-SNAPSHOT"
description = "PDF_Reader"
java.sourceCompatibility = JavaVersion.VERSION_19

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
